[libraries]
assertJ = "org.assertj:assertj-core:3.27.6"
commonsLogging = "commons-logging:commons-logging:1.3.5"
jackson = "com.fasterxml.jackson.core:jackson-databind:2.20.1"
#using version range to avoid suggested upgrades, 3.0.1 is last with annotations
jsr305 = { module = "com.google.code.findbugs:jsr305", version = "[3.0.1, 3.0.1]" }
junit4 = "junit:junit:4.13.2"
logback = "ch.qos.logback:logback-classic:1.5.21"
reactorBom = "io.projectreactor:reactor-bom:2025.0.1"
slf4jApi = "org.slf4j:slf4j-api:2.0.17"
snakeYaml = "org.yaml:snakeyaml:2.5"
spring = "org.springframework:spring-core:7.0.1"
thymeleaf = "org.thymeleaf:thymeleaf:3.1.3.RELEASE"

[plugins]
sass = { id = "io.miret.etienne.sass", version = "1.6.0" }
shadow = { id = "com.gradleup.shadow", version = "8.3.6" }
spotless = { id = "com.diffplug.spotless", version = "8.1.0" }
